name: New Framework Test

on:
  pull_request:
    branches:
      - 'main'
      - '3.0'
      - 'new_test_framework'
    paths:
      - 'test/cases/**'
      - 'test/new_test_framework/**'
      - 'test/ci/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-TDengineNewFramework
  cancel-in-progress: true

jobs:
  test-new-cases:
    uses: taosdata/.github/.github/workflows/new-framework-test.yml@main
    with:
      tdinternal: false
