name: TDengine taostools coverage
description: Coverage test for taostools

on:
  pull_request:
    branches:
      - 'cover/tools-3.0'
      - 'cover/3.0'
    paths:
      - 'tools/taos-tools/**'
      - '!tools/taos-tools/**/*.md'
      - '!.github/workflows/**'
  workflow_dispatch:
    inputs:
      specified_source_branch:
        description: 'Enter the source branch name of TDengine'
        required: true
        type: string
      specified_target_branch:
        description: 'Enter the target branch name of TDengine'
        required: true
        type: string
      specified_pr_number:
        description: 'Enter the PR number of TDengine'
        required: true
        type: string
    


concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-
    ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || inputs.specified_target_branch }}-
    ${{ github.event_name == 'pull_request' && github.event.pull_request.number || inputs.specified_pr_number }}-TDengine
  cancel-in-progress: true

env:
  WK: '/var/lib/jenkins/workspace/TDinternal/'
  WKC: '/var/lib/jenkins/workspace/TDinternal/community'

jobs:
  run-tests-on-linux:
    uses: taosdata/.github/.github/workflows/run-taostools-coverage-tests.yml@test_coverage
    with:
      tdinternal: false
      specified_source_branch: ${{ github.event_name == 'pull_request' && 'unavailable' || inputs.specified_source_branch }}
      specified_target_branch: ${{ github.event_name == 'pull_request' && 'unavailable' || inputs.specified_target_branch }}
      specified_pr_number: ${{ github.event_name == 'pull_request' && 'unavailable' || inputs.specified_pr_number }}